name: flutter_ui_practice
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
